### ISSUE TITLE
The install script fails if the SA password contains special characters

### ISSUE THREAD

**Issue by dev-nt90** [chriseaton/docker-adventureworks#2]
When the following command is run:
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -d master -i master.sql

And the SA_PASSWORD parameter is set to a password with special characters, the following will be output:
Sqlcmd: 'master': Unknown Option

As a result, the AdventureWorks backup is not restored.

To fix, wrap the SA_PASSWORD param in quotes.

**Comment by chriseaton** [comment]
Fixed by @dev-nt90
